### ISSUE TITLE
Reorganize Test Grid Tabs

### ISSUE THREAD

**Issue by jeremyeder** [openshift/osde2e#25]
* Create a new top-level tab: `redhat-openshift-dedicated`
* Create sub-tabs for prod and stage test results.
* Adjust existing tests to report into new tabs.
* Do not delete old test results or the tab.
* Mentally prepare for future additional tabs (beyond prod and stage).

@ethernetdan

**Comment by ethernetdan** [comment]
Put in kubernetes/test-infra#12843 to make changes

**Comment by ethernetdan** [comment]
Merged and active.
