### ISSUE TITLE
Create pipelines for stage and prod

### ISSUE THREAD

**Issue by jeremyeder** [openshift/osde2e#26]
We need to be able to run osde2e against arbitrary UHC endpoints, starting with stage and prod, and eventually adding int.

Each result should have it's own tab within testgrid (https://github.com/openshift/osde2e/issues/25)

@ethernetdan

**Comment by ethernetdan** [comment]
Created https://gitlab.cee.redhat.com/service/jjb/merge_requests/257 to start running in prod

**Comment by ethernetdan** [comment]
Job is running but fails because quota in prod has not been configured. Keeping open until starts passing.

**Comment by ethernetdan** [comment]
Running successfully (first run https://prow.k8s.io/view/gcs/redhat-openshift-osd-e2e/logs/osd-prod-4.1/31)
