### ISSUE TITLE
Issue with login

### ISSUE THREAD

**Issue by jmjava** [openshift/osde2e#31]
I am having issues running tests with a newly created redhat developer account.

I can use my developer credentials to get the UHC token via 

uhc login --user=... --password=...

then i can get token via 

uhc token

I also have a newly created AMZ web services account.  And created a key for a user with Admin rights.  

Setting these 3 env params but it's not letting me create the cluster.

UHC_TOKEN: The token used to authenticate with the OSD environment.
AWS_ACCESS_KEY_ID: AWS key ID used by OSD to install clusters.
AWS_SECRET_ACCESS_KEY: AWS access key used by OSD to install clusters.

2019/06/06 21:23:18 Creating cluster 'ci-cluster-1-hbzb6'...
Failure [0.001 seconds]
[BeforeSuite] BeforeSuite 
/home/ubuntu/go/src/github.com/openshift/osde2e/setup.go:25

  failed to setup cluster for testing
  Unexpected error:
      <*errors.errorString | 0xc00035eea0>: {
          s: "could not launch cluster: couldn't create cluster: can't get access token: either user name and password or client identifier and secret must be provided",
      }
      could not launch cluster: couldn't create cluster: can't get access token: either user name and password or client identifier and secret must be provided
  occurred

  /home/ubuntu/go/src/github.com/openshift/osde2e/setup.go:30

2019/06/06 21:23:18 CLUSTER_ID is not set, likely due to a setup failure. Skipping AfterSuite...

Turned on OSD debug and see:

019/06/08 09:28:56 OpenID token URL wasn't provided, will use 'https://developers.redhat.com/auth/realms/rhd/protocol/openid-connect/token'
2019/06/08 09:28:56 OpenID client identifier wasn't provided, will use 'uhc'
2019/06/08 09:28:56 OpenID client secret wasn't provided, will use ''
2019/06/08 09:28:56 Bearer token expires in 3m53.218356161s
2019/06/08 09:28:56 Refresh token isn't available
2019/06/08 09:28:56 Request method is GET
2019/06/08 09:28:56 Request URL is 'https://api.stage.openshift.com/api/clusters_mgmt/v1/versions'
2019/06/08 09:28:56 Request header 'Accept' is 'application/json'
2019/06/08 09:28:56 Request header 'Authorization' is omitted
2019/06/08 09:28:56 Request header 'User-Agent' is 'UHC/0.1.14'
2019/06/08 09:28:57 Response status is '401 Unauthorized'
2019/06/08 09:28:57 Response status code 401
2019/06/08 09:28:57 Response header 'Content-Length' is '131'
2019/06/08 09:28:57 Response header 'Content-Type' is 'application/json'
2019/06/08 09:28:57 Response header 'Date' is 'Sat, 08 Jun 2019 13:28:56 GMT'
2019/06/08 09:28:57 Response header 'Server' is 'Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips'
2019/06/08 09:28:57 Response header 'Set-Cookie' is 'e5ba9b5d94759f62ffa2852bda2cfc72=d6f088d5eaef8696973590d38782301e; path=/; HttpOnly; Secure'
2019/06/08 09:28:57 Response body follows
2019/06/08 09:28:57 {
  "code": "GATEWAY-401",
  "href": "/api/gateway/v1/errors/401",
  "id": "401",
  "kind": "Error",
  "reason": "Access to resource isn't authorized"
}

I guess the basic redhat developer access is not enough to run this?

UPDATE: I see something in the uhc-cli docs about having a domain registered with Route53 - in process of registering and will try again. 

-john

**Comment by jmjava** [comment]
I tried https://github.com/openshift-online/uhc-sdk-go/blob/master/examples/create_cluster.go without any luck.   I still cannot create a cluster

**Comment by jeremyeder** [comment]
Let's sync about this via email.
