### ISSUE TITLE
Fix production tests

### ISSUE THREAD

**Issue by ethernetdan** [openshift/osde2e#34]
The production test job is currently not running due to a configuration issue. It should be fixed and restarted.

**Comment by jeremyeder** [comment]
Testing in production is blocked until https://jira.coreos.com/browse/SREP-1572 is solved.

**Comment by ethernetdan** [comment]
Tests have started running in prod https://k8s-testgrid.appspot.com/redhat-osd-prod#osd-prod-4.1
