### ISSUE TITLE
Additional tests from OpenShift extended test suite

### ISSUE THREAD

**Issue by ethernetdan** [openshift/osde2e#35]
osde2e currently runs a limited set of tests from the [OpenShift extended test suite](https://github.com/openshift/origin/tree/master/test/extended). 

We should expanded the set of tests to run taking in account:
* affect on total duration of osde2e runs (max: 2hrs)
* tests that could be disruptive to osde2e

**Comment by jeremyeder** [comment]
Closing as we're not going to duplicate existing tests that are already run in Origin.
