### ISSUE TITLE
Ensure osde2e always uses the "default" ClusterImageSet

### ISSUE THREAD

**Issue by jeremyeder** [openshift/osde2e#39]
The [JJB jobs](https://gitlab.cee.redhat.com/service/jjb/blob/master/ci-ext/osd-e2e/40-jobs.yaml#L22) specify ```version: "4.1"``` but this means we're not testing the default CIS.  More importantly we're not moving past 4.1.0 (all runs are on this version now in both stage and prod).

- The latest CIS is 4.1.2 and is the default CIS in prod.
- Interestingly, there are two CIS labeled as default=true in stage.  See the [conversation](https://github.com/openshift/osde2e/issues/39) in Slack for more info on that.

Please update osde2e pipelines deploy whatever is labeled as the default CIS:
```api.openshift.com/default=true```

Please also account for how this might break testgrid or other places where ```{version}``` or ```CLUSTER_VERSION``` is used.

**Comment by jhernand** [comment]
To get the default version you can do this:

```go
response, err := connection.ClustersMgmt().V1().Versions().List().
        Search("default = 't'").
        Size(1)
if err != nil {
        ...
}
version := response.Items().Get(0)
if version = nil {
        ...
}
```
