### ISSUE TITLE
go get fails with unknown revision 000000000000

### ISSUE THREAD

**Issue by drpaneas** [openshift/osde2e#390]
```go
$ go get github.com/openshift/osde2e/cmd/osde2e
go: found github.com/openshift/osde2e/cmd/osde2e in github.com/openshift/osde2e v0.0.0-20200518142820-7daa37b719e4
go get: github.com/openshift/osde2e@v0.0.0-20200518142820-7daa37b719e4 requires
	github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20190926160646-a61144936680 requires
	github.com/openshift/api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

See the unknown revision issue.

**Comment by jeefy** [comment]
To build/use the binary you'll have to clone down the repo then build it via Make. 

In the future we may start cutting official releases as velocity slows. /cc @meowfaceman

**Comment by meowfaceman** [comment]
Oh hrm. This isn't really expected -- I would assume that anyone would be able to go get this binary without needing to do this. I'm confused about this particular error -- AFAICT, this weird version being shown for openshift/api isn't reflected in the operator-lifecycle-manager repo.

**Comment by jeefy** [comment]
Actually, this just worked for me.

@drpaneas What OS / Version of Go are you using? 

For reference, I'm on Ubuntu with go 1.14.2

**Comment by drpaneas** [comment]
I am using:

`go version go1.14 darwin/amd64`

Hmmmm, I just run it again from a golang docker container and it works. So I guess this must be something related to my system and not in general. Strange though ...

```
 docker run -it golang /bin/bash
Unable to find image 'golang:latest' locally
latest: Pulling from library/golang
376057ac6fa1: Pull complete
5a63a0a859d8: Pull complete
496548a8c952: Pull complete
2adae3950d4d: Pull complete
039b991354af: Pull complete
0cca3cbecb14: Pull complete
59c34b3f33f3: Pull complete
Digest: sha256:1e36f8e9ac49d5ee6d72e969382a698614551a59f4533d5d61590e3deeb543a7
Status: Downloaded newer image for golang:latest
root@f641e23b4937:/go#
root@f641e23b4937:/go# go get github.com/openshift/osde2e/cmd/osde2e
root@f641e23b4937:/go# osde2e
2020/05/19 14:01:09 Updating the osde2e binary.
Usage: osde2e <flags> <subcommand> <subcommand args>

Subcommands:
	commands         list all command names
	flags            describe all known top-level flags
	help             describe subcommands and their syntax
	query            Queries Prometheus results.
	test             Runs end to end tests on a cluster using the provided arguments.
	weather-report   Produces a report based on osde2e test runs.
	weather-report-to-slack  Produces a report based on osde2e test runs and sends it to a Slack webhook.


Use "osde2e flags" for a list of top-level flags
root@f641e23b4937:/go# go version
go version go1.14.3 linux/amd64
```

I also asked @RiRa12621 to reproduce it, but it works in his machine as well

```
$ go version
go version go1.14.2 darwin/amd64
```

So this must be something related to my system. I will close the issue and sorry for the noise.

**Comment by RiRa12621** [comment]
There’s a good chance that there was a time correlation with GitHub itself having issues

**Comment by meowfaceman** [comment]
@RiRa12621 Thanks for pointing that out. I was so confused about why this was working at all given the nature of the problem, hahaha.
