### ISSUE TITLE
Archive prometheus database 

### ISSUE THREAD

**Issue by jeremyeder** [openshift/osde2e#42]
Copy the raw prometheus database up to test artifacts.

**Comment by ethernetdan** [comment]
Looks like Origin uses an [`oc` invocation](https://github.com/openshift/release/blob/cb5b338349afb8a80d7bdc8efb86ff7f17fc5041/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L811). Planning to use the runner Pod to do the same.

**Comment by jeremyeder** [comment]
Nice.  Just to be clear, I think we should archive the prometheus database for all tests, not just the workload one we just discussed.

**Comment by ethernetdan** [comment]
Ack, sounds good
