### ISSUE TITLE
Determine which Regions and AZs OSD can be installed to

### ISSUE THREAD

**Issue by jeremyeder** [openshift/osde2e#5]
- List all AZs within all supported AWS regions
  - We support all regions *EXCEPT* GovCloud, China and Osaka
  - Must use AZ ID's, not friendly-names (e.g. NOT us-east-1a)
- Create an OSD that spreads to all AZ within that region (# of worker nodes should be equal to the number of AZs within the region)
- Iterate through all supported AWS regions
- Identify total number of clusters that this test would create
  - Need to know approx cost
- Publish the pass/fail list somewhere (where eventually UHC could consume it)

- Identify if it possible to query the AWS (or Azure) API to determine instance availability

@jhernand do you have a reference to the AZ "id" (which does not get remapped).

**Comment by jeremyeder** [comment]
Sample code for 3.11:

https://github.com/openshift/openshift-tools/blob/prod/ansible/roles/lib_utils/library/oo_vpc_subnets_calc.py

**Comment by ethernetdan** [comment]
Fixed in UHC.
