### ISSUE TITLE
Add logging tests

### ISSUE THREAD

**Issue by jeremyeder** [openshift/osde2e#61]
This test needs to:
* Install the Logging operator
* Run logging load tests /cc @mffiedler  
* Upgrade (if test is in the upgrade pipeline)
* Post-upgrade health checks?

**Comment by mffiedler** [comment]
See https://github.com/openshift/svt/blob/master/openshift_scalability/content/logtest/ocp_logtest-README.md for a possible approach to load generation

**Comment by jeremyeder** [comment]
@jewzaam @mwoodson any existing logging/upgrade tests that we run in 3.x that we should carry forward?

**Comment by mwoodson** [comment]
Unfortunately we don't have any logging tests that I can think of in v3.  The V3 testing has been done when we upgrade a cluster, and see how it works. 

Let's tag other's for their thoughts:

@blrm  @dak1n1 @robotmaxtron

**Comment by dak1n1** [comment]
The only one I can think of is the ES health check. It's a test that can be run against one of the ElasticSearch pods to gauge the health of the ES cluster. It's just hitting an API, but usually we do the test from within the ES pod because it's easier to get the client TLS certs that way.

```
[root@ded-int-aws-master-ip-172-31-18-78.us-west-2.compute.internal ~]# oc -n openshift-logging rsh -c elasticsearch $espod health 
Wed Jul 10 19:21:10 UTC 2019
epoch      timestamp cluster    status node.total node.data shards  pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1562786471 19:21:11  logging-es green           3         3   2175 1088    0    0        0             0                  -                100.0%
```
