### ISSUE TITLE
Test newest Hive with a set of older ClusterImageSets once per week

### ISSUE THREAD

**Issue by jeremyeder** [openshift/osde2e#69]
@dgoodwin if you can add any more thoughts.

**Comment by dgoodwin** [comment]
Today we have no coverage that as Hive changes are rolled out, old ClusterImageSets will always still work. Perfect world we'd have something run on every Hive PR that tests it against every supported ClusterImageSet, but this is probably not feasible. An option might be to test oldest supported, newest, and maybe something in the middle.

**Comment by meowfaceman** [comment]
I've filed SDAR-22 on the CoreOS JIRA to cover this as per @jeremyeder's recommendation. I'm going to close this issue and pick up the JIRA to work this.
