### ISSUE TITLE
add 4.1->4.2  and 4.2->4.2 upgrade tests to all pipelines

### ISSUE THREAD

**Issue by jeremyeder** [openshift/osde2e#77]

**Comment by jeremyeder** [comment]
Right now the existing upgrade jobs are looking at 4-stable.  So it will be 4.1->4.1 until a 4.2 build shows up in 4.2-stable.

We need to be able to select a specific minor release in order to have a pipeline for each of the $subject variants.

@stevekuznetsov how does the Origin CI do this?

**Comment by stevekuznetsov** [comment]
Do you mean to ask how to configure an upgrade job in the CI system? Today it's as easy as asking for `upgrade: true` in the configuration. [Example](https://github.com/openshift/release/blob/c8b8299eb1dce7cc82f4831beda5d3fb6987e784/ci-operator/config/openshift/origin/openshift-origin-master.yaml#L231-L235). If you mean to ask what happens under the covers, it's a bit more complicated.

**Comment by meowfaceman** [comment]
Closing this and using https://jira.coreos.com/browse/SDAR-23 instead.
