### ISSUE TITLE
Documentation claims min go version of 1.13 however go.mod requires 1.16

### ISSUE THREAD

**Issue by dry923** [openshift/osde2e#892]
In the ReadMe it states that the required minimum version of go is 1.13. On the next line it tells the user to install the appropriate dependencies via go mod tidy. This, however, requires version 1.16 of go and fails with anything below that.

Snip from go.mod
```
module github.com/openshift/osde2e

go 1.16
```

**Comment by georgettica** [comment]
touching some doc stuff here (one line but still) so I will link here #896
