### ISSUE TITLE
github pager show MOA instead of ROSA

### ISSUE THREAD

**Issue by georgettica** [openshift/osde2e#897]
see picture regarding https://openshift.github.io/osde2e/
![Screen Shot 2021-08-25 at 18 01 36](https://user-images.githubusercontent.com/11993626/130815906-c86f973e-017f-4c10-90d6-b1c4c460f454.png)

**Comment by jbpratt** [comment]
/remove-lifecycle frozen

This whole thing has been unused/deprecated. This issue can be closed, we still need to clean up the automation that is pushing the data.
