### ISSUE TITLE
Enable UHC SDK debug logs

### ISSUE THREAD

**Issue by jeremyeder** [openshift/osde2e#9]
Like this:

https://github.com/openshift-online/uhc-sdk-go/blob/722cf7c05ce9e442a11a3008aad490c1c075fac5/examples/get_cluster_logs.go#L35-L53

@ethernetdan

**Comment by ethernetdan** [comment]
We already have a `DEBUG_OSD` env var to do this, I'll enable it for the nightly

**Comment by ethernetdan** [comment]
Blocked on openshift-online/uhc-sdk-go#32
