### ISSUE TITLE
Add check for existence of Ginkgo Focus flags

### ISSUE THREAD

**Issue by clcollins** [openshift/osde2e#90]
Gingko supports focused specs by using `FDescribe`, `FContext`, `FIt` in place of the standard `Describe`, `Context` and `It` functions: https://onsi.github.io/ginkgo/#focused-specs

The same is true of "P" or "X" to mark Pending Specs, but there's a valid reason to allow inclusion of the Pending flags.

This is helpful for local development, but if committed to the CI pipeline accidentally, it cause the pipeline to skip all unfocused specs.

It would be helpful to have an automated test be added that checks for focused specs in PRs?  A `grep` would probably be enough, or running `ginkgo unfocus` on a clone of the PR and checking for changed files would work.

**Comment by meowfaceman** [comment]
This was supported and then fleshed out in https://issues.redhat.com/browse/SDCICD-171, so I think this is good.
